'clips': ''
'clips_folder': 'C:\Users\matthewp.W221N\Documents\analysis\clips_baa'
dlc_network_posecfg: 'C:\Windows\System32\BigArena2-phillips_m_g-2019-05-08\dlc-models\iteration-1\BigArena2May8-trainset95shuffle1\test'
'dlc_network_snapshot': 'C:\Windows\System32\BigArena2-phillips_m_g-2019-05-08\dlc-models\iteration-1\BigArena2May8-trainset95shuffle1\train\snapshot-800000'
'scorer': 'DeepCut_resnet50_BigArena2May8shuffle1_800000'
'store trial videos': True
